export enum EnemyID {
  crab = 0,
  seagull = 1,
  turtle = 2,
  gangsterCrab = 3,
  greenSlime = 4,
  redSlime = 5,
  blueSlime = 6,
  kingSlime = 7,
  rat = 8,
  giantRat = 9,
  wolf = 10,
  deer = 11,
  bandit = 12,
  goblinScout = 13,
  troll = 14,
}
