export enum EnemyID {
  crab = 0,
  seagull = 1,
  turtle = 2,
  gangsterCrab = 3,
  greenSlime = 4,
  redSlime = 5,
  blueSlime = 6,
  kingSlime = 7,
  rat = 8,
  giantRat = 9,
  wolf = 10,
  deer = 11,
  goblinScout = 12,
  bandit = 13,
  mountainBat = 14,
  goat = 15,
  goblinScavenger = 16,
  troll = 17,
  // Mawood — Elderwood Wilds (Zone 6)
  forestSpider = 18,
  gnollScout = 19,
  corruptedSapling = 20,
  gnollWarchief = 21,
  // Mawood — Deepwood (Zone 7)
  elderSpider = 22,
  forestBear = 23,
  bogSkeleton = 24,
  treantSprout = 25,
  gnarledTreant = 26,
  // Mawood — Upper Canopy (Zone 8)
  harpy = 27,
  giantEagle = 28,
  canopyBandit = 29,
  harpyMatriarch = 30,
}
